[package]
name = "tiny-hello-rs"
version = "0.1.0"
authors = ["John Askew"]
edition = "2018"

[dependencies]
winapi = { version = "0.3" , features = ["ntdef", "winuser"] }

[profile.dev]
panic = "abort"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"